name: Check

on:
  pull_request:
  push:
    branches:
      #- main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - run: gofmt -l -d .
      - run: go vet .

      - run: go test -race -covermode=atomic -coverprofile=coverage.out .
      - uses: codecov/codecov-action@v2
